Hasan/action sheet improvement 4
deriv-com/quill-design pull request #127
Opened 2024-01-02 10:11 UTC by hasan-deriv

Changes:

* fixed dragging issue
* exported action sheet context consumer hook

2024-01-05 04:03 UTC, meenakshi-deriv approved these changes

2024-01-09 07:45 UTC, prince-deriv requested changes

2024-01-09 07:45 UTC, prince-deriv commented on src/components/action-sheet/trigger/index.tsx
> +  if (!Icon) return <Button onClick={handleOpen} {...restProps} />
```suggestion
 return <Button onClick={handleOpen} {...restProps} />
```

2024-01-09 07:47 UTC, prince-deriv submitted a review, later dismissed

2024-01-09 08:26 UTC, prince-deriv approved these changes

2024-01-09 08:26 UTC, merged