Fasih/DPROD-3003/Implement message or alert section
deriv-com/quill-design pull request #133
Opened 2024-03-15 09:06 UTC by fasihali-deriv

Implement message information section

<img width="485" alt="Screenshot 2024-03-15 at 5 05 28 PM" src="https://github.com/deriv-com/quill-design/assets/121229483/7c54c167-305c-459c-b475-3f0909796272">

2024-03-15 10:42 UTC, hasan-deriv requested changes

2024-03-15 10:42 UTC, hasan-deriv commented on src/components/section-message/information/index.tsx
> +              'flex flex-col',
```suggestion
            className={qtJoin(
              'flex flex-col',
```

2024-03-15 10:42 UTC, hasan-deriv commented on src/components/section-message/information/index.tsx
> +                  {title}
here as well

2024-03-15 10:42 UTC, hasan-deriv commented on src/components/section-message/information/index.tsx
> +                    qtMerge(SectionMessageMessageSizeCVA({ size })),
here as well

2024-03-15 10:42 UTC, hasan-deriv commented on src/components/section-message/information/index.tsx
> +                  )}
here as well

2024-03-15 10:42 UTC, hasan-deriv commented on src/components/section-message/information/index.tsx
> +                  )}
here as well

2024-03-15 10:42 UTC, hasan-deriv commented on src/components/section-message/information/index.tsx
> +                    qtMerge(SectionMessageMessageSizeCVA({ size })),
```suggestion
                    qtMerge(SectionMessageDescriptionSizeCVA({ size })),
```

2024-03-15 10:46 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +                  )}
Done

2024-03-15 10:46 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +                  )}
Done

2024-03-15 10:47 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +                    qtMerge(SectionMessageMessageSizeCVA({ size })),
Fixed

2024-03-15 10:47 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +                    qtMerge(SectionMessageMessageSizeCVA({ size })),
Fixed

2024-03-15 10:47 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +                  {title}
fixed

2024-03-15 10:47 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +              'flex flex-col',
fixed

2024-03-18 02:56 UTC, fasihali-deriv commented on src/components/section-message/information/index.tsx
> +          </div>
Thanks @hasan-deriv for raising this. 
I was only able to remove one div.

2024-03-18 03:08 UTC, hasan-deriv approved these changes

2024-03-18 03:34 UTC, habib-deriv approved these changes

2024-03-18 03:34 UTC, merged